/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hangman;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Objects;


/**
 *
 * @author alahm
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setIcon();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HangMan");
        setBackground(new java.awt.Color(56, 72, 78));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(340, 155));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(56, 72, 78));
        jPanel1.setLayout(null);

        btnExit.setBackground(new java.awt.Color(56, 72, 78));
        btnExit.setForeground(new java.awt.Color(49, 203, 17));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/icons/close_window_26px.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        jPanel1.add(btnExit);
        btnExit.setBounds(40, 90, 70, 26);

        btnStart.setBackground(new java.awt.Color(56, 72, 78));
        btnStart.setForeground(new java.awt.Color(49, 203, 17));
        btnStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hangman/icons/play_26px.png"))); // NOI18N
        btnStart.setText("Start");
        btnStart.setBorder(null);
        btnStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStartMouseClicked(evt);
            }
        });
        jPanel1.add(btnStart);
        btnStart.setBounds(170, 90, 70, 26);

        jLabel1.setForeground(new java.awt.Color(51, 204, 0));
        jLabel1.setText("Name");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(12, 19, 50, 16);

        jTextField1.setBackground(new java.awt.Color(56, 72, 78));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(12, 41, 236, 27);

        jComboBox1.setBackground(new java.awt.Color(56, 72, 78));
        jComboBox1.setForeground(new java.awt.Color(52, 182, 17));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard" }));
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(316, 41, 81, 22);

        jLabel2.setForeground(new java.awt.Color(0, 204, 51));
        jLabel2.setText("Difficulty level");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(316, 19, 90, 16);

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 70, 236, 10);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 410, 130);

        setBounds(0, 0, 425, 168);
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartMouseClicked
        // TODO add your handling code here:
       enterTheGame();

    }//GEN-LAST:event_btnStartMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitMouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
        enterTheGame();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnStart;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons/icon.png")));
    }
    private void enterTheGame(){
     String name;
        String difficultyLevelChosen = Objects.requireNonNull(jComboBox1.getSelectedItem()).toString();
        if (jTextField1.getText().isEmpty()) {
            name = "Anonymous";
        } else {
            name = jTextField1.getText();
        }
       new Game(name, difficultyLevelChosen).setVisible(true);
        setVisible(false);
    }
}
